### ISSUE TITLE
Grails app missing

### ISSUE THREAD

**Issue by Omnipresent** [cloudfoundry/java-test-applications#19]
I came across this repository while searching for sample Grails applications that are built to be deployed to CloudFoundry. The README.md mentions that `grails-application` however, I haven't been able to find any `grails-application`. Is the README.md missing some information or am I just not seeing the `grails-application`

**Comment by cgfrost** [comment]
Hi Omnipresent

The application was removed earlier this year and unfortunately the Readme wasn't updated. We will ensure the Readme is updated.

https://github.com/cloudfoundry/java-test-applications/commit/14a702a428c7bfa147a86ebb46db1d3c1b78dffc

**Comment by cgfrost** [comment]
FYI https://www.pivotaltracker.com/story/show/131978235

**Comment by nebhale** [comment]
@Omnipresent Grails 3 applications are effectively Spring Boot applications and therefore there was no longer a need for a separate application type (that's covered by the `java-main-application`).  As @cgfrost mentions, it was removed, but the README was not updated as well.
