### ISSUE TITLE
Play Framework app mentioned, but no longer existing

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/java-test-applications#20]
The `play-application` is mentioned in https://github.com/cloudfoundry/java-test-applications#applications but was removed via 14a702a. I was looking for an alternative, minimal Play Framework app but it seems hard to find one on Github. Any chance to point me to one that's know to work or is Play Framework no longer supported by the Java buildpack?

Thanks in advance.

**Comment by nebhale** [comment]
The Play framework up through 2.4 is still supported by the buildpack.  2.5 broke compatibility and there hasn't been a strong request for work to bring this up to date.  I'm happy to take contributions from the Play community for the changes, but as it stands now, we'll just be leaving the current support in place and have no plans to either improve or remove it.
